### ISSUE TITLE
Only search comments

### ISSUE THREAD

**Issue by daveriess** [codeclimate/codeclimate-fixme#11]
Fixme has yelled at us for having 'xxx' show up in strings and for having 'bug' show up in comments describing a bug that a particular test solves for.

It seems to me that fixme should only trigger off of strings that are allcaps,  followed by a colon, and in comments.

FWIW.

**Comment by mrrsm** [comment]
Agreed!
This is very annoying and we have no way to suppress the errors (inline at least). 
I agree if it was limited to all caps with a colon after it that should solve most of my problems at least.

**Comment by mrrsm** [comment]
This should be as simple as taking the -i out of the grep statement I think.  Maybe I can do some tests and submit a PR

**Comment by ABaldwinHunter** [comment]
@mrrsm Thanks for the suggestion. We've updated the `fixme` engine to only look for all caps. We're planning to make the engine more discriminate in the future.

Closing this issue for now.

**Comment by omarmeky** [comment]
+1

**Comment by omarmeky** [comment]
I've had it complain about "XXX" in HTML content (not comments). Can we improve this?
