### ISSUE TITLE
Finding `fixme` in .codeclimate.yml

### ISSUE THREAD

**Issue by devinus** [codeclimate/codeclimate-fixme#17]
```
== .codeclimate.yml (1 issue) ==
5: fixme found [fixme]
```

**Comment by ABaldwinHunter** [comment]
@devinus thanks for the feedback! This issue sounds similar to an [existing one](https://github.com/codeclimate/codeclimate-fixme/issues/15), so I'm going to close in favor of that.

We're currently working on improving the engine to be smarter about the `fixme`s it finds.

In the meantime, you can also exclude the `.codeclimate.yml` file from analysis, as we've done for the [fixme engine](https://github.com/codeclimate/codeclimate-fixme/blob/master/.codeclimate.yml#L14) itself.
