### ISSUE TITLE
Engine not found

### ISSUE THREAD

**Issue by buren** [codeclimate/codeclimate-fixme#3]
```
$ codeclimate engines:enable fixme
Engine not found. Run 'codeclimate engines:list' for a list of valid engines.
```

codeclimate CLI version 0.0.10 (OSX)

**Comment by ABaldwinHunter** [comment]
Hi @buren, sorry about that! Thanks for your feedback. This engine tool is currently in progress and we're working to get it ready for release soon.

**Comment by buren** [comment]
Ok, thanks :+1:
