### ISSUE TITLE
fixme flags its own configuration

### ISSUE THREAD

**Issue by amiel** [codeclimate/codeclimate-fixme#37]
<img width="371" alt="screenshot 2016-05-19 16 46 29" src="https://cloud.githubusercontent.com/assets/27160/15413005/50c3aec4-1de1-11e6-847d-4b514b1d67ee.png">

Could it automatically ignore `.codeclimate.yml`?

**Comment by ABaldwinHunter** [comment]
@amiel thanks for the feedback! We considered that behavior and ultimately opted not to include it,  thinking that there could exist legitimate `FIXME`s in a config file. E.g.:

```yaml
#engines:
# TODO: configure eslint engine
# TODO: add .codeclimate.yml to exclude_paths
```

We may try to make the engine smarter in the future, but for now there are two easy workarounds:
1) Add the `.codeclimate.yml` to your top level `exclude_paths`, or the engine-specific exclude paths for fixme:

.codeclimate.yml
```yaml
engines:
  fixme:
    enabled: true
    exclude_paths: 
    - .codeclimate.yml
```
2) [Exclude the fingerprint](https://docs.codeclimate.com/docs/marking-false-positives)

Going to close this issue for now but please feel free to reopen if you run into any other issues!

**Comment by amiel** [comment]
Thanks for the workaround
