### ISSUE TITLE
Incorrectly detecting XXX

### ISSUE THREAD

**Issue by rachel-carvalho** [codeclimate/codeclimate-fixme#41]
I have a piece of code that consumes Google's Adwords API and I need to set a value to 'XXX', like so:
```ruby
{
  default_revenue_currency_code: 'XXX'
}
```

But FIXME is detecting this piece of code as a fixme content. Do you guys have a suggestion of how to work around this? Thank you!

For reference, their docs: https://developers.google.com/adwords/api/docs/reference/v201605/ConversionTrackerService.AdWordsConversionTracker#defaultrevenuecurrencycode

**Comment by dblandin** [comment]
Hi @rachel-carvalho,

The fixme engine detects (and emits issues for) any of the following strings: `TODO`, `FIXME`, `HACK`, `BUG`, `XXX`.

You may want to [ignore this particular issue by fingerprint](https://docs.codeclimate.com/v1.0/docs/marking-false-positives), [ignore the entire file](https://docs.codeclimate.com/docs/excluding-files-and-folders), or [specify your own fixme strings](https://github.com/codeclimate/codeclimate-fixme#configuration).

**Comment by rachel-carvalho** [comment]
I didn't realize I could ignore this occurrence specifically, that's awesome, because I don't want to disable the check for XXX entirely. Thanks @dblandin! I'll just close the issue.

**Comment by dblandin** [comment]
@rachel-carvalho Happy to help! 👍
