### ISSUE TITLE
Tutorial has broken link to main js file

### ISSUE THREAD

**Issue by tedmiston** [codeclimate/codeclimate-fixme#44]
In the [tutorial blog post](http://blog.codeclimate.com/blog/2015/07/07/build-your-own-codeclimate-engine/), it mentions:

> The meat of the actual engine is in the index.js file...

Then links to this page which 404s:

https://github.com/codeclimate/codeclimate-fixme/blob/master/index.js

I think this is the file it's looking for:

https://github.com/codeclimate/codeclimate-fixme/blob/master/lib/fix-me.js

**Comment by maxjacobson** [comment]
Thanks! Updated
