### ISSUE TITLE
When using config strings, it shows those errors on .codeclimate.yml file itself

### ISSUE THREAD

**Issue by steventran06** [codeclimate/codeclimate-fixme#45]
It should automatically exclude itself? I had to add an exclude_path to the .codeclimate.yml file so it would go away.
![screen shot 2016-12-19 at 6 04 14 pm](https://cloud.githubusercontent.com/assets/11085115/21335950/1f6d9946-c617-11e6-8747-fe7c650bc842.png)

**Comment by maxjacobson** [comment]
Hi @steventran06 - thanks for pointing that out. It should be resolved now.
