### ISSUE TITLE
TODO found in wrong file

### ISSUE THREAD

**Issue by zverok** [codeclimate/codeclimate-fixme#49]
![image](https://user-images.githubusercontent.com/129656/29767032-8e705e4e-8be9-11e7-9967-3f5336ba1ef3.png)

Yes, I have `TODO.md` in my repo, with my private plans/ideas for the library, and it is `.gitignore`d. I believe it should not be reported ¯\\\_(ツ)_/¯

**Comment by maxjacobson** [comment]
Hi @zverok!

I come bearing two options:

1. Use [issue statuses](https://docs.codeclimate.com/v1.0/docs/issues#section-issue-statuses) to mark this as an invalid issue, which will make it stop showing up
1. Use [exclude paths](https://docs.codeclimate.com/v1.0/docs/issues#section-issue-statuses) to exclude the gitignore file for this engine

It's possible we could try to avoid flagging this issue in the first place, but it's not immediately clear what would the new rule be that would be intuitive to everybody.

What do you think?

**Comment by zverok** [comment]
Well, of course I can use either of two options. But for me, checking `.gitignore` (and, in fact, all of other `.<filename>`s? -- all in all, it is UNIX it is a convention to name "invisible" files) clearly looks like a bug.

**Comment by pointlessone** [comment]
I can imagine a `.gitignore` that looks like this:
```
tmp/
*.swp
# TODO: all the build artifacts
```

Do you think those should not be reported?

**Comment by zverok** [comment]
Hm... Could make some sense, probably. Though, it is a comment, not filename, like in my example.

**Comment by pointlessone** [comment]
This engine is not particularly clever. It doesn't know the _meaning_ of the string. It just look for strings in your project. Just as the ReadMe says.

**Comment by zverok** [comment]
OK, I guess ¯\\\_(ツ)_/¯
