### ISSUE TITLE
Docker image is quite big...

### ISSUE THREAD

**Issue by vovimayhem** [codeclimate/codeclimate-fixme#50]
Hi!

I think the current fixme image is bigger than it has to given the current docker common practice...

I think we can shrink it down to around 70MB from 212MB if we change the base to `node:*-alpine`

I'm sending a PR for that in some minutes...

**Comment by vovimayhem** [comment]
.... just an update: I've just noticed this engine uses system grep :/ will take me a little while...

**Comment by pointlessone** [comment]
I wonder if this engine can be redone on top of [codeclimate/codeclimate-grep](https://github.com/codeclimate/codeclimate-grep). That one is only 64.7 MB and is a bit more general version of this one.

**Comment by vovimayhem** [comment]
@pointlessone I ended up with a 58MB image on #51 for this one... but yeah, I think less engines that do more would be cool

**Comment by vovimayhem** [comment]
However, if we were to base `fixme` from `grep` engine, we'd make sure we're still honouring the `fixme` configuration, and make sure those grep rules are applied accordingly, which would be a different kind of work... maybe for another time?

**Comment by wfleming** [comment]
I'm a big fan of the reduced image size in #51, so thank you for doing that @vovimayhem !

FWIW I don't think we'd be interested in rebuilding this engine on top of our own `grep` engine though, at least not anytime soon. One unanticipated but appreciated benefit of the simplicity of the `fixme` engine we've noticed is that it makes a very nice reference implementation of an engine that developers can use to understand the practical applications of our [spec](https://github.com/codeclimate/spec) without getting bogged down in meaty details of particular languages or tools. So I think keeping it entirely separate from the `grep` engine is helpful for that, and it's so simple that I don't think there's an excessive maintenance overhead to keeping them separate.

**Comment by vovimayhem** [comment]
@wfleming We can make both the fixme Docker image and the grep Docker image to share the most possible number of layers, reducing the download time in case one or another has already been downloaded.

**Comment by vovimayhem** [comment]
(although they already do)

**Comment by dblandin** [comment]
Addressed with #51. Thanks!
